language: go

go:
  - 1.1
  - 1.2
  - tip

install:
  - go get github.com/discoproject/goworker/jobpack
  - go get github.com/discoproject/goworker/worker
  - go get github.com/discoproject/goworker/jobutil
